# These are supported funding model platforms

github: [colgreen] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sharpneat # Replace with a single Patreon username
open_collective: colgreen # Replace with a single Open Collective username
